/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Pot,
  PotInterface,
} from "../../../../../contracts/src/interfaces/IMaker.sol/Pot";

const _abi = [
  {
    inputs: [],
    name: "chi",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dsr",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rho",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Pot__factory {
  static readonly abi = _abi;
  static createInterface(): PotInterface {
    return new utils.Interface(_abi) as PotInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Pot {
    return new Contract(address, _abi, signerOrProvider) as Pot;
  }
}
