[package]
name = "typescript-macro"
version = "0.1.0"
edition = "2021"

[lib]

proc-macro = true

[dependencies]
heck = "0.5.0"
js-sys = "0.3.64"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
wasm-bindgen = "0.2.86"
