[package]
name = "delv-core"
version = "0.1.0"
edition = "2021"

[dependencies]
# external
ethers = "2.0.14"
js-sys = "0.3.64"
thiserror = "1.0"
wasm-bindgen = "0.2.86"

# internal
fixedpointmath = "0.16.8"
