import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "doc",
      id: "sdk/index",
    },
    {
      type: "category",
      label: "Guides",
      items: ["sdk/guides/position", "sdk/guides/react"],
    },

    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "doc",
          id: "sdk/api-reference/classes/ReadHyperdrive",
          label: "Read Hyperdrive",
        },
        {
          type: "doc",
          id: "sdk/api-reference/classes/ReadWriteHyperdrive",
          label: "Write Hyperdrive",
        },
      ],
    },
  ],
};

export default sidebars;
