export const faqData = [
  {
    key: "faq1",
    question: "What is a Long?",
    answer: (
      <div className="flex flex-col gap-4">
        <p>
          Long positions in Hyperdrive allow users to earn a fixed rate on their
          deposits. When a user opens a Long position, they receive an
          agreed-upon future value that is redeemable 1:1 at maturity.
        </p>
        <p>
          Example: A user deposits 1.00 stETH in a market offering a 5% fixed
          APR (net of fees) for a 12-month position duration. They can redeem
          1.05 stETH one year from now.
        </p>
      </div>
    ),
  },
  {
    key: "faq2",
    question: "What is a Short?",
    answer: (
      <div className="flex flex-col gap-4">
        <p>
          Short positions in Hyperdrive enable users to earn a multiplied
          variable rate that may result in higher implied yields. Users pay the
          market fixed rate upfront as margin and earn variable yield on the
          full capital this margin is backing, leading to a profit (or loss)
          depending on which rate performed better.{" "}
        </p>
        <p>
          Example: A user could pay 0.05 stETH upfront to earn the yield
          generated by a total of 1.05 stETH for a year (assuming a 5% fixed
          APR, 12-month position duration). If the variable yield works out to
          be 0.08 stETH (8% APY), they will be exposed to an implied return of:
          <br />
          <br />
          = variable yield * (1 / fixed rate)
          <br />
          = 0.08 * (1 / 0.05)
          <br /> = 0.08 * 20
          <br />= 1.6x on their principal investment (before pool fees)
        </p>
      </div>
    ),
  },
  {
    key: "faq3",
    question: "What are the benefits of providing liquidity?",
    answer: (
      <div>
        <span>
          Liquidity providers (LPs) take potential revenue from 3 different
          sources: <br /> - Trading fees from longs and shorts being opened and
          closed by traders. <br /> - Variable rate on their idle capital being
          deployed to the underlying yield source. <br /> - Profit (or loss)
          resulting from taking the other side of traders’ positions.
          <br />
          Furthermore, LP capital isn&rsquo;t tied to a specific maturity date,
          so these benefits remain until the funds are withdrawn by the LP.{" "}
          <br /> Learn more about{" "}
          <a
            className="underline"
            href="https://delv-tech.notion.site/LP-Profitability-0acf6928b88c4a33875221aa15ca62d2"
          >
            LP Profitability
          </a>
          .
        </span>
      </div>
    ),
  },
  {
    key: "faq4",
    question: "Can I close a position before maturity?",
    answer: (
      <div>
        <span>
          Yes, longs and shorts can be closed at any time (except in rare cases,
          learn more in the{" "}
          <a
            href="https://delv-tech.notion.site/AMM-Checkpoints-11eefd1e09974551949803e16fe48afa"
            className="underline"
          >
            docs
          </a>
          ). However, closing these positions before maturity implies selling
          them to the AMM at the current market price. In other words, positions
          that are closed early won&rsquo;t get the initially expected rate of
          return, since their exit value depends on market activity. <br />
          <br />
          Liquidity Provider (LP) positions don&rsquo;t have a maturity date, so
          LP funds can be withdrawn at any time as long as they&rsquo;re not
          currently backing other long or short positions; if they are, LPs will
          receive Withdrawal Shares that represent pending withdrawals that
          still share the same benefits of regular LP capital. Learn more in the{" "}
          <a
            href="https://delv-tech.notion.site/LP-Shares-9d3d21330909494d83608eddf7d518c5"
            className="underline"
          >
            LP Shares
          </a>{" "}
          section of our docs.
        </span>
      </div>
    ),
  },
  {
    key: "faq5",
    question: "How do LP positions work?",
    answer: (
      <div>
        <span>
          You open an LP position by providing base asset to the AMM. This
          increases the AMM&rsquo;s capacity for longs and shorts. LP capital is
          then used to back long and short positions opened by traders.
          <br />
          <br />
          LPs can withdraw their capital at any time, but if part of it is
          currently backing open positions, the AMM will temporarily keep that
          part and give Withdrawal Shares to the LP until there is enough idle
          liquidity available to replace that capital. <br />
          <br />
          When long or short positions are closed, the liquidity used to back
          them is freed up and used to buy back Withdrawal Shares, at which
          point LPs can complete their pending withdrawal process. <br />
          <br />
          Learn more in the{" "}
          <a
            href="https://delv-tech.notion.site/LP-Shares-9d3d21330909494d83608eddf7d518c5"
            className="underline"
          >
            LP Shares
          </a>{" "}
          section of our docs.
        </span>
      </div>
    ),
  },
];
