import {
  aeroUsdcAero,
  cbeth,
  morphoCbethUsdc,
  mwEth,
  mwEurc,
  mwUsdc,
  snars,
  stkWell,
} from "./base";
import { gnosisSgyd, gnosisWsteth, sxdai } from "./gnosis";
import { lineaEzeth, rseth } from "./linea";
import {
  eeth,
  ezeth,
  lidoSteth,
  makerDsr,
  morphoSusdeDai,
  morphoUsdeDai,
  morphoWstethUsda,
  morphoWstethUsdc,
  reth,
  sgyd,
  stusd,
  susde,
  susds,
  usds,
} from "./mainnet";
import { YieldSource, YieldSourceId } from "./types";

export const yieldSources: Record<YieldSourceId, YieldSource> = {
  eeth,
  makerDsr,
  lidoSteth,
  morphoSusdeDai,
  morphoUsdeDai,
  morphoWstethUsdc,
  morphoWstethUsda,
  morphoCbethUsdc,
  reth,
  ezeth,
  gnosisWsteth,
  sxdai,
  cbeth,
  stusd,
  lineaEzeth,
  rseth,
  usds,
  susds,
  mwEth,
  stkWell,
  snars,
  mwEurc,
  mwUsdc,
  aeroUsdcAero,
  susde,
  sgyd,
  gnosisSgyd,
};
