import {
  aeroUsdcAero,
  cbeth,
  morphoCbethUsdc,
  mwEth,
  mwEurc,
  mwUsdc,
  snars,
  stkWell,
} from "src/yieldSources/base";
import { gnosisSgyd, gnosisWsteth, sxdai } from "src/yieldSources/gnosis";
import { lineaEzeth, rseth } from "src/yieldSources/linea";
import {
  eeth,
  ezeth,
  lidoSteth,
  morphoSusdeDai,
  morphoUsdeDai,
  morphoWstethUsda,
  morphoWstethUsdc,
  reth,
  sgyd,
  skyDsr,
  stusd,
  susde,
  susds,
  usds,
} from "src/yieldSources/mainnet";
import { YieldSourceConfig, YieldSourceId } from "src/yieldSources/types";

export const yieldSources: Record<YieldSourceId, YieldSourceConfig> = {
  eeth,
  skyDsr,
  lidoSteth,
  morphoSusdeDai,
  morphoUsdeDai,
  morphoWstethUsdc,
  morphoWstethUsda,
  morphoCbethUsdc,
  reth,
  ezeth,
  gnosisWsteth,
  sxdai,
  cbeth,
  stusd,
  lineaEzeth,
  rseth,
  usds,
  susds,
  mwEth,
  stkWell,
  snars,
  mwEurc,
  mwUsdc,
  aeroUsdcAero,
  susde,
  sgyd,
  gnosisSgyd,
};
