/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iMakerSol from "./IMaker.sol";
export type { iMakerSol };
export type { IERC20 } from "./IERC20";
export type { IERC20Mint } from "./IERC20Mint";
export type { IERC20Permit } from "./IERC20Permit";
export type { IForwarderFactory } from "./IForwarderFactory";
export type { IHyperdrive } from "./IHyperdrive";
export type { IMultiToken } from "./IMultiToken";
