[package]
name = "ts-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# external
heck = "0.5.0"
quote = "1.0"
syn = "1.0"
wasm-bindgen = "0.2.92"

# workspace
ts-type = { path = "../ts-type" }
